-- 自动生成的数据模块: Enemy
local Enemy = {
    ["1"] = {
        ["onlyID"] = "1",
        ["EnemyID"] = 10010001,
        ["Name"] = "病毒-基础型",
        ["Type"] = 1,
        ["ChapterAppearance"] = 1,
        ["MaxHP"] = 100,
        ["Abilities_Desc"] = "基础病毒，没有特殊能力",
    },
    ["2"] = {
        ["onlyID"] = "2",
        ["EnemyID"] = 10010002,
        ["Name"] = "病毒-分裂型",
        ["Type"] = 1,
        ["ChapterAppearance"] = 2,
        ["MaxHP"] = 150,
        ["Abilities_Desc"] = "被消灭时会分裂成两个小病毒",
    },
    ["3"] = {
        ["onlyID"] = "3",
        ["EnemyID"] = 10010003,
        ["Name"] = "病毒-防御型",
        ["Type"] = 1,
        ["ChapterAppearance"] = 3,
        ["MaxHP"] = 300,
        ["Abilities_Desc"] = "拥有护盾，需要先破盾才能造成伤害",
    },
    ["4"] = {
        ["onlyID"] = "4",
        ["EnemyID"] = 10010004,
        ["Name"] = "病毒-快速型",
        ["Type"] = 1,
        ["ChapterAppearance"] = 4,
        ["MaxHP"] = 80,
        ["Abilities_Desc"] = "移动速度较快，但生命值较低",
    },
    ["5"] = {
        ["onlyID"] = "5",
        ["EnemyID"] = 10010005,
        ["Name"] = "病毒-爆炸型",
        ["Type"] = 1,
        ["ChapterAppearance"] = 5,
        ["MaxHP"] = 120,
        ["Abilities_Desc"] = "死亡时会对周围造成伤害",
    },
    ["6"] = {
        ["onlyID"] = "6",
        ["EnemyID"] = 10020001,
        ["Name"] = "细菌-基础型",
        ["Type"] = 2,
        ["ChapterAppearance"] = 6,
        ["MaxHP"] = 200,
        ["Abilities_Desc"] = "基础细菌，攻击力较高",
    },
    ["7"] = {
        ["onlyID"] = "7",
        ["EnemyID"] = 10020002,
        ["Name"] = "细菌-繁殖型",
        ["Type"] = 2,
        ["ChapterAppearance"] = 7,
        ["MaxHP"] = 180,
        ["Abilities_Desc"] = "每隔一段时间会繁殖一个新的细菌",
    },
    ["8"] = {
        ["onlyID"] = "8",
        ["EnemyID"] = 10020003,
        ["Name"] = "细菌-免疫型",
        ["Type"] = 2,
        ["ChapterAppearance"] = 8,
        ["MaxHP"] = 250,
        ["Abilities_Desc"] = "对某些类型的攻击免疫",
    },
    ["9"] = {
        ["onlyID"] = "9",
        ["EnemyID"] = 10020003,
        ["Name"] = "细菌-免疫型2",
        ["Type"] = 2,
        ["ChapterAppearance"] = 8,
        ["MaxHP"] = 250,
        ["Abilities_Desc"] = "对某些类型的攻击免疫",
    },
}

return Enemy